"""crear tabla curso

Revision ID: 5391357c9494
Revises: 5bc7e239fcae
Create Date: 2026-06-17 00:54:04.592492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5391357c9494'
down_revision = '5bc7e239fcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
